### ISSUE TITLE
Damage -> Gust speed should be "relative" instead of "true"

### ISSUE THREAD

**Issue by nawre** [ls4096/sailnavsim-core#3]
Relative wind gusts speed should be taken into account for damage, not true speeds.

**Comment by ls4096** [comment]
This is a good point, but I think it should really take both absolute and relative values into account. For example, I think it's safe to say that a 55 knot gust in 50 knot winds is more likely to cause greater damage than a 25 knot gust in 18 knot winds, despite the fact that the relative gust value of the former (by any interpretation of the word "relative") is less than that of the latter.

I agree that there is room for improvement here, but it's not clear how to come up with a model that's both realistic as well as sufficiently simple enough to reason about for sailing/racing purposes, but I'm open to suggestions.

**Comment by nawre** [comment]
Have you heard about fuzzy logic introduced by Lotfi Zadeh in 1965 ? I think you could apply fuzzy logic to determine  damage from environnement. 

_Perfect for simulation of situations that arise in real life either because of the inexactness of the environment, or because of the inexactness/imprecision of the available data._   Source : DOI 10.1145/21850.253069

You could take  and combine multiple input parameters to determine damage in a realistic way. Add a little bit of random to the result to not have a full deterministic engine : even if two saiboats a few meters away from each other are struck by a 60 knots gust, one could get 40 % damage, but the other one could get only 35 %.

**Comment by ls4096** [comment]
I have recently realized that another valid interpretation of this request is that damage ought to be accrued based on the wind gust speed of the [apparent wind](https://en.wikipedia.org/wiki/Apparent_wind) rather than the true wind (as it is currently implemented), in which case I agree this makes a lot of sense! Perhaps I misunderstood the original request, but if it's the above then this is definitely something I would like to have implemented.

**Comment by ls4096** [comment]
Damage mode with an option to have damage calculated based on the apparent wind (instead of true wind) gusts is now implemented in v1.12.0.
